services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: dummy_sndentalsite
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: WpD@tabase2025!
    volumes:
      - db_data:/var/lib/mysql
      - ./dummy_sndentalsite.sql:/docker-entrypoint-initdb.d/dummy_sndentalsite.sql

  web:
    build: .
    container_name: sndentalcollege_dental_app
    ports:
      - "9075:80"
    volumes:
      - ./sndentalcollege_dental:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: dummy_sndentalsite
      MYSQL_USER: wordpress
      MYSQL_PASSWORD:	WpD@tabase2025!

volumes:
  db_data: